### ISSUE TITLE
Verify method used for file search

### ISSUE THREAD

**Issue by plbenveniste** [neuropoly/slicer-manual-annotation#1]
Opening this issue to check how the file search is done using the yml file to find corresponding files in the dataset directory. 
Currently it is done using glob. Maybe using rglob could be better. 

Tagging @maxradx @valosekj @jcohenadad

**Comment by maxradx** [comment]
Hi @plbenveniste ,
Yes. In fact, to get the cases_path among sub-directories, I used "`       self.cases_path = sorted(glob(
            f'{self.current_dir}{os.sep}{self.FOLDER_ORG}*{os.sep}anat'
            f'{os.sep}*{self.CONTRAST}{self.VOLUME_FILE_TYPE}'))` . Please note that the code has been refractored in the meantime, so now the main script comes from @delphinepilon

**Comment by maxradx** [comment]
Agree that could be better. The current module (4f3bd23) uses glob to extract the filepath of the cases in subfolder using `      self.CasesPaths = sorted(glob(f'{self.CurrentFolder}{os.sep}**{os.sep}{INPUT_FILE_EXTENSION}', recursive = True))
`. If BIDS structure is imposed, a preliminary BIDS validator test the folder organization. The actual method is able to load in the Slice Viewer the different cases. If eventually we want to use rglob, then we could create a new issue a that time.
