### ISSUE TITLE
Segment Editor Improvements

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#11]
This issue is about improving the use of the segment editor module in 3D Slicer.

Action tasks:

- [ ] Automates a predefined size of the paint button selector (mouse cursor) when opening the segment editor
- [x] Automates filling of a space if a closed-form is done
- [ ] Ensure that window width levels are easily adjusted when in the segment editor (related to mouse customization options)

**Comment by jcohenadad** [comment]
> Automates filling of a space if a closed-form is done

Isn't it what https://slicer.readthedocs.io/en/latest/user_guide/modules/segmenteditor.html#mask-volume does?

**Comment by maxradx** [comment]
Will look forward it. Some function like scissors allow to perform similar task (but scissor draw on all slices and not only on one slice). Also, even if it says it does, sometimes, implementation can be tricky (even if it looks easy, it crashes or something and this requires debugging)

**Comment by delphinepilon** [comment]
The tool Lasso Paint is now available in the branch SlicerCART. To be incorporated into main. It uses the Scissor functionality without drawing on all the slices.

**Comment by maxradx** [comment]
Done. Tool Lasso Paint implemented.
