### ISSUE TITLE
Automated generation of a QC report (or executing shell script file using python interactor in 3D Slicer)

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#15]
3D Slicer has its own python version. This can lead to troubleshooting when trying to run a shell script (e.g. from a python script) that execute a programs using also python. An example is about using the SCT QC report from a shell script file in 3D Slicer.
Non-working example:
<img width="731" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/4af9b9a6-676b-4c4f-b323-8fca735732a4">

**Comment by jcohenadad** [comment]
> 3D Slicer has its own python version. This can lead to troubleshooting when trying to run a shell script (e.g. from a python script) that execute a programs using also python. An example is about using the SCT QC report from a shell script file in 3D Slicer.

I'm not sure I understand the purpose of this issue. The title "Automates generation of a QC report" is about the automatic generation of QC report, while the description is about the fact that 3D slicer has its own python version. Can you please clarify what this issue is about? Is it about a new desired feature? If so what exactly is needed?

**Comment by maxradx** [comment]
Ok. From the current python file, it is possible to execute a shell script file. However in ./bin folder, there is a file named 'from_sct_qc.sh'  that has been designed for executing the sct_qc command from sct, and this does not work since when it is tried to execute the script, at some point, it says it missed some requirements (e.g. Darwin's ...) (and the sct_qc works correctly if ran from the terminal).

**Comment by maxradx** [comment]
Outdated. Transposed in 2 new issues : [issue 94](https://github.com/neuropoly/slicer-manual-annotation/issues/94) and [issue 95](https://github.com/neuropoly/slicer-manual-annotation/issues/95)
