### ISSUE TITLE
Create a shell scripts (and/or QPushButton) that automates the use of git

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#16]
This issue is about BIDS and git versioning.

- [ ] Create functions that automates the git add *, git commit and git push process (for example for a segmentation mask) in the derivates folder, assuming a BIDS convention. (This would need to consider how to handle/remove the label naming in the segment masks files and also if the new mask is empty ...)
- [ ] Using a QPushbutton
- [ ] Using execution of a shell script file
- [ ] Once completed, a fractoring of current versioning system (e.g. _vXX) could be done

**Comment by jcohenadad** [comment]
I'm not sure I'm in favour of automatic the use of git, and especially git-annex. People have to know exactly what they push, what branch they are working on, if the origin branch is ahead of the working branch, and if so, manually merge origin to the working branch, if there are conflicts, fix them, etc. Automating this is cause for trouble

**Comment by maxradx** [comment]
Ok! Good point. Instead, would it be better to create a Push button/Selection Box that allows for selecting the version of the mask/file that the user would like to 'push' to derivates, and from it gives the responsibility for the user for using git (from your previous advice, on the other hand, I remembered that minimizing GUI buttons is essential if using a GUI: is that correct?)

**Comment by maxradx** [comment]
Outdated. See discussion above (not relevant, and risky).
