### ISSUE TITLE
Correct toggle segmentation minor bugs when 2 labels instead of 3 or others

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#18]
This issue is about a little bug discovered in toggle segmentation versions when using 2 labels instead of 3.
In brief, it loads a 3rd masks even if only 2 labels are selected, so this create discordance in the number of versions.
Example below.
<img width="731" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/6d8b4d5d-ee12-4919-9ad6-2c0e272c500b">

**Comment by maxradx** [comment]
relates to issue #34

**Comment by delphinepilon** [comment]
Closure explanation: The interface and code has changed quite a bit. This issue is no longer applicable so I am closing it.
