### ISSUE TITLE
add a marker for segmentation already done (change colour of names in case list)

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#22]
In order to keep track of the cases that have already been segmented by the **current annotator**, it would be great if we could have a marker indicating this state. It could be either changing the colour of the names of the files in the case list (as done in [this code](https://github.com/laurentletg/ICH_SEGMENTER_V2/commit/dd47086be898a437e895664c14df3ab72c48a7e8)), or it could be an icon indicating that the segmentation has already been done.

**Comment by maxradx** [comment]
Yes! I though the same thing. I think to change the color of the name that appears in the UI case list would be great (example below). For example:
- Automatic --- no segmentation mask already done
- Yellow/Orange -- segmentation
If mask_loaded (display the latest version in the slice viewer if found):
- If multiple version for a segmentation_mask, color could be different (e.g. blue)

- [ ] Set color has to be done in the UI case list.
<img width="512" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/cb002e78-5d32-448f-be8e-784f2de8b5f3">
