### ISSUE TITLE
Implement / Adapt the Assessment feature from branch "slicer-manual-annotation/mb_code"

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#23]
**Configurations**

- number of cases to use for the training / assessment of new annotators

**Specifications**

- choose a volumes directory (as per usual)
- choose a directory containing the ground truth segmentations validated by an expert 
- make the randomly selected case anonymous to avoid annotators peeking at the answers
- enable the segmentation task by the annotator (using the timer)
- compare the new segmentation with the ground truth
- compute metrics such as the Dice score 
- generate an overlap of these segmentations and make apparent the false positives and false negatives 
- generate a recap document with the results of the annotator

This feature has been implemented in the branch "slicer-manual-annotation/mb_code". It must be transferred to the main branch (created by SlicerCART code). 

**Post-tasks**

After implementation / adaptation, evaluate the necessity of the following issues related to the Assessment module:

- [[Issue 7](https://github.com/neuropoly/slicer-manual-annotation/issues/7)]
- [[Issue 8](https://github.com/neuropoly/slicer-manual-annotation/issues/8)]
- [[Issue 9](https://github.com/neuropoly/slicer-manual-annotation/issues/9)]
- [[Issue 13](https://github.com/neuropoly/slicer-manual-annotation/issues/13)]
- [[Issue 14](https://github.com/neuropoly/slicer-manual-annotation/issues/14)]

**Comment by maxradx** [comment]
Outdated. Will open another issue when discussion about integrating such feature will be done.
