### ISSUE TITLE
Publication on 3D Slicer's Extensions Manager 

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#24]
- Research the requirements for publication on 3D Slicer's Extensions Manager
- Create relevant issues to achieve this goal

**Comment by maxradx** [comment]
related to [issue 55](https://github.com/neuropoly/slicer-manual-annotation/issues/55).

**Comment by maxradx** [comment]
Included in https://github.com/neuropoly/slicer-manual-annotation/issues/70. Closed to avoid duplication.
