### ISSUE TITLE
Use the explicitly stated label value instead of the order in the list of labels

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#28]
When the file extension is `.nii.gz`, the specified label value is not saved properly when the label values are not consecutive and starting at 1, i.e., if they do not imitate the natural numbers. 

**Known issue :** 
Currently, it doesn't seem possible to save segments with segment ids other than the natural numbers according to the segment order in the segment list of the segment editor.

https://discourse.slicer.org/t/how-to-change-segmentid-of-existing-segmentations/11254

**Possible workaround:**

- Create empty segments that will be placed between the segments that correspond to the labels specified in the configuration file. 
- Place the segments that correspond to the labels in the correct order according to their respective label values [`...GetSegmentation().SetSegmentIndex(segment_id, segment_value - 1)`]
- Save the segmentation as is and the label values should be alright (hypothesis that should be confirmed by testing)

**Comment by maxradx** [comment]
Addressed by @AcastaPaloma  and merge in PR 81
