### ISSUE TITLE
when it will be supported, accept to impose BIDS on modality == CT

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#29]
[CT in BIDS format (forum)](https://neurostars.org/t/ct-in-bids-format/9129/2)

[Docs WIP du forum](https://docs.google.com/document/d/1fqnJZ18x5LJC8jiJ8yvPHUGFzNBZ6gW2kywYrUKWtuo/edit#heading=h.bs4ewiqm3qrq)

**Comment by maxradx** [comment]
Addressed in the actual code (4f3bd23)
