### ISSUE TITLE
Make display of timer optional i.e. configurable upon startup 

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#33]

**Comment by maxradx** [comment]
Indeed, I would remove any timer display in the module and make segmentation time of each segment (as currently done) automated.
Rationale: the user should not see any timer while performing annotation since this can cause [Hawthorne effect](https://catalogofbias.org/biases/hawthorne-effect/) (bias)

**Comment by delphinepilon** [comment]
**Specifications**

- add a new configuration (like "display_timer_requested") in `general_config.yml`
- add a new checkbox or combobox in the class `SlicerCARTConfigurationSetupWindow` for this
- set the visibility of the timer to follow the value of this new configuration 
```
self.ui.lcdNumber.setVisible(bool_value)
```

Note : take another parameter as an example like `is_keyboard_shortcuts_requested`.

**Expected behaviour**
If the configuration value is `False`, the timer should not be visible to the user. If the configuration value is `True`, the timer should be visible to the user. In both cases, the duration is written to the `*SegmentationInformation.csv` file. It is a useful metric that should be kept.

**Comment by AcastaPaloma** [comment]
should we still use start/pause/restart buttons for the case where the configuration value is `False`? If not, what would be the cue to start the timer in the background?

**Comment by delphinepilon** [comment]
I like the idea of keeping the start / pause / restart buttons. It gives the user the opportunity to temporarily stop the timer in the middle of an annotation. Otherwise, the duration of the annotation could be less accurate. I don't know what others think?

**Comment by AcastaPaloma** [comment]
Display of timer configurable under configure segmentation window
