### ISSUE TITLE
Allow loading of previously created segmentations

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#34]
In the case that segmentations were previously created without using this extension, it would be nice if the users could load these segmentations for further modification through the GUI. 

- check whether the existing labels are compatible with the label configuration 
- load the segments in the correct colour

**Comment by laurentletg** [comment]
Tested current version does not work even if I add _v01 at the end of segmentation files and go in the config file.

**Comment by maxradx** [comment]
Issue 114 is a pre-requisite to solve this issue. Issue 114 fixed.
