### ISSUE TITLE
SlicerCART new main branch is not found as a module by 3D Slicer

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#36]
This issue is about fixing the use of the adapted Slicer CART module, so it appears automatically (e.g. in Examples --- Slicer Manual Annotation) when 

In fact, when the most recent version of this repo is being downloaded, the module is not found by 3D Slicer even after restart.
<img width="1039" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/7f618141-ba40-4ce4-a400-aea4bda0bf60">

<img width="423" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/40a52406-334a-4d17-ab53-0293f8d931c1">

**Comment by delphinepilon** [comment]
Hi @maxradx,

As described in the README, we must "add the path of the folder containing the SlicerCART.py". 

Here is a screenshot of my 3D Slicer configuration.

<img width="655" alt="3D_Slicer_config" src="https://github.com/neuropoly/slicer-manual-annotation/assets/43301868/97c3b65d-95fa-4163-bb0e-562d0c7b9b77">

Let me know if this doesn't solve the issue!

**Comment by maxradx** [comment]
Thanks for the input! Previously, there were some requirements that we could install, and now there isn't. I would need to install PyQt5 for example. the code to execute in the python console that install the requirments could be put in the README?
<img width="752" alt="image" src="https://github.com/neuropoly/slicer-manual-annotation/assets/142258732/fc318fa3-4758-4e9d-8565-cf356a7f15dd">

**Comment by delphinepilon** [comment]
Thanks for your suggestion! I've added this section to the README.
