### ISSUE TITLE
Enabling measurement from keyboard shortcut in the slice viewer

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#37]
**Is your feature request related to a problem? Please describe.**
Inability to draw measurements of structure from the mouse when a key on the keyboard is pressed. 

**Describe the solution you'd like**
E.g. pressing 'm' on the keyboard could change the mouse cursor so it enabling it to draw measurement on the display viewer.

**Describe alternatives you've considered**
This is an additional feature that has not been implemented yet.

**Comment by delphinepilon** [comment]
Hi @maxradx, I was wondering if you would like this information to be saved and if so, should it be saved as a measurement in the segmentation information `.csv` or as another layer in the segmentation file (`.nii.gz`) say as an additional label or in a new file altogether? 

I think we should start by adding a QPushButton for this, and then applying a keyboard shortcut.

Thank you in advance for the clarifications!

**Comment by AcastaPaloma** [comment]
Are we talking rough, straight-line measurement?

**Comment by AcastaPaloma** [comment]
@maxradx when you have time, could you go check the pull request supposed to cover this issue? i added a qpushbutton to measure the distance, but I am still looking for edge cases. all measurement information is saved in the .csv file

**Comment by laurentletg** [comment]
Great feature. 
We should eventually discuss if such features should instead be implemented in separate modules to keep the core codebase simpler and easier to maintain. Another option would be to add a configurable option pane (e.g. loading qt push buttons and specifying callbacks . In such a scenario, each user could have their own version of the module configured for a specific use case (extending the core SlicerCART functionalities but without impacting the main SlicerCART codebase). Maybe something similar to the module wizard in Slicer.
