### ISSUE TITLE
Importing packages on fresh install

### ISSUE THREAD

**Issue by laurentletg** [neuropoly/slicer-manual-annotation#38]
**Describe the bug**

SlicerCART fails to load on a fresh install of 3D Slicer. 
These packages needs to be manually installed in the python interactor, not ideal. 
```py
slicer.util.pip_install('PyQt5')
slicer.util.pip_install('bids-validator')
```
> Note that Slicer has a version of Qt (Qt for Python which has a more liberal license than PyQt5). it is already imported. It seems that  `PyQt5 import QtCore` be replaced by `qt.QCoreApplication`

**To Reproduce**
Add the module and try to load it. 

**Expected behavior**
Module checks if the extension is available and if not pip install it. 
I am unsure about how extensions are managed when going through the official Slicer extension. 

**Screenshots**

<img width="807" alt="image" src="https://github.com/user-attachments/assets/30cf9396-c18b-41e5-beca-a7cc6b14fab7">

**Comment by jcohenadad** [comment]
Relevant posts:
- https://discourse.slicer.org/t/module-for-internal-dosimetry-in-nuclear-medicine/3317/14
- https://discourse.slicer.org/t/how-to-use-a-python-package-in-an-extension/12736/2

**Comment by maxradx** [comment]
Addressed by recent development. WOrks well in the actual code (4f3bd23)
