### ISSUE TITLE
Refactor and avoid parallel development

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#4]
This issue is about adopting a convention with consensus in order to avoid parallel development in the programming code, and ensure compatibility between developements.

Here are the links for a convention that could be adapted (PEP8)
* [PEP8 style guide official documentation](https://peps.python.org/pep-0008/)
* [Polytechnique Montreal Home-Made Guide for programming style (in French)](https://github.com/INF1007-Gabarits/Guide-codage-python)

In brief:
* MyClass for naming a Class;
* MY_CONSTANT for naming a CONSTANT
* my_variable for naming a variable
* define_my_function() for naming a function (always start with an action verb)
* TODO: for naming To Dos in the code
* One space line has been added between each function for clarity
* Useful comments are strongly encouraged
* *Some of the code may not respects this convention, since previous related work did not seem to use any and some unmodified blocks has not been refractored in that context

Action tasks:
- [ ] Discuss with Dr. Letourneau-Guillon and team about conventino that they used @llaurentletg
- [ ] Refractor the remaining parts of the code (from both team) to unify it

**Comment by jcohenadad** [comment]
Having a [`CONTRIBUTING.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file would be a good starting point.

**Comment by maxradx** [comment]
> Having a [`CONTRIBUTING.md`](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file would be a good starting point.

Done! 
Keeping issue opened since this is will evolve according to future discussions with Dr. Letourneau-Guillon's team.

**Comment by maxradx** [comment]
*Officially added CONTRIBUTING.md and there is now a template proposed for code contribution when opening an issue. Please feel free to modify/give feedback to optimize its adoption. [CONTRIBUTING.md](https://github.com/neuropoly/slicer-manual-annotation/blob/main/CONTRIBUTING.md)

**Comment by laurentletg** [comment]
I also suggest linking or copying the following[ style recommendations from the Slicer team.](https://slicer.readthedocs.io/en/latest/developer_guide/style_guide.html#python)


Follow the Slicer repository Flake8 configuration and run python -m pre_commit run --all-files to confirm compliance.
Text encoding: UTF-8 is preferred, Latin-1 is acceptable
Comparisons:
To singletons (e.g. None): use ‘is’ or ‘is not’, never equality operations.
To Booleans (True, False): don’t ever compare with True or False (for further explanation, see PEP 8).
Prefix class definitions with two blank lines
Imports
Grouped in order of scope/commonallity
Standard library imports
Related third party imports
Local apps/library specific imports
Slicer application imports and local/module imports may be grouped independently.
One package per line (with or without multiple function/module/class imports from the package)
Naming conventions: when [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) and Slicer naming conventions conflict, Slicer wins.

**Comment by laurentletg** [comment]
By the way, the previous code needs refactoring. It's a mess (shame on me—it was a learning experience) and not PEP8 compliant, so feel free to refactor it.

**Comment by maxradx** [comment]
Issue outdated. Now we have a [coding standard,](https://github.com/neuropoly/slicer-manual-annotation/blob/main/CONTRIBUTING.md) and a way of working in team: 
- 1 module to be developed in team;
- 1 issue = 1 PR;
- Submit PR before merging into the main branch;
- Regular biweekly meetings.
