### ISSUE TITLE
Make it possible to create various segmentation tasks and switch between them

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/slicer-manual-annotation#42]
Suggestion from @laurentletg

Currently, a use case is defined with a [config file](https://github.com/neuropoly/slicer-manual-annotation/blob/39aa6197c03221f369ddfbcdad1a15cd9a9515cd/SlicerCART/src/general_config.yml). If users would like to create multiple tasks (eg: segmentation of brain MS lesions, segmentation of brain tumors, etc.) it would be nice for the user to be able to generate multiple config files and then select the desired one from the Slicer module. 

This would probably require changing the module name in the CMake file, python filename (and script), and .ui file (unless there is a way to do this directly in the extension wizard) -

**Comment by delphinepilon** [comment]
This is now supported. The configuration files are saved in the output folder. Therefore, a user is able to continue working on multiple projects by simply selecting one of the project's output folder and the correct configurations will be applied to the extension. In addition, this output folder can be shared between members of a same team for collaboration and/or revision.

I have made some videos describing the new configuration GUI, here is the [link](https://drive.google.com/drive/folders/1DrwUyciaZGmifhIl60TkqIT7fM4BUg2l)!

**Comment by maxradx** [comment]
Relying on @delphinepilon  comment above. Issue solved.
