### ISSUE TITLE
Overriding keyboard shortcuts - interference with built-in Slicer functions

### ISSUE THREAD

**Issue by laurentletg** [neuropoly/slicer-manual-annotation#45]
**Problem**
- The configurable keyboard shortcuts  do not work in the segment editor module after switching from the SlicerCART module (e.g. 'i' to toggle intensity masking). 

**Potential solutions**
- An option would be to refactor so that we can enable or disable the keyboard shortcuts in the SlicerCART module through the configuration file.
- Another option would be to better integrate probably through the use of observers and  integration with the remainder of the modules.

**Comment by delphinepilon** [comment]
I've added the option to include or exclude the keyboard shortcuts. This option enables the configuration of the keyboard shortcuts in the GUI. Further work could be done to possibly integrate these shortcuts across other extensions.
