### ISSUE TITLE
QIntValidator not working as expected 

### ISSUE THREAD

**Issue by delphinepilon** [neuropoly/slicer-manual-annotation#53]
**Describe the bug**
The QIntValidator restrictions imposed on QLineEdits are not taken into account in the SlicerCART configuration windows. 

**To Reproduce**
1. Go to the SlicerCART extension.
2. Select the "New configuration" option.
3. Click on "Next".
4. Select the option "CT" in the modality field. 
5. See that it is possible to write letters in the fields "Window Level" and "Window Width". 

**Expected behaviour**
The typed input should be restricted to integers, as requested in the code. 

**Screenshots**
<img width="799" alt="image" src="https://github.com/user-attachments/assets/f76cfff5-6de6-4c6f-a40c-765e9c92405a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version : Sonoma 14.1.1

**Additional context**
The problem also occurs in the configuration window for a single label, in both the fields for the HU range and the 3 fields dedicated to the RGB values of the colour. This QIntValidator for the colours should only accept values within 0 to 255.

**Comment by maxradx** [comment]
To solve issue 59, this has been required and adressed in PR 81. Issue 53 now fixed.
