### ISSUE TITLE
Create a configuration window to configure Segmentation 

### ISSUE THREAD

**Issue by AcastaPaloma** [neuropoly/slicer-manual-annotation#59]
Change ''Configure labels'' to ''Configure Segmentation'' to include label configuration, timer configuration, the semi-automatic PHE segmentation tool and other settings configuration-only related.

![image](https://github.com/user-attachments/assets/f919e058-3a81-438f-9c13-13d47b689311)

**Comment by maxradx** [comment]
This is now solved from merging PR 81 in the main branch.
