### ISSUE TITLE
Value cannot be changed on new label

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/slicer-manual-annotation#66]
version: eef16bcb5e84cf73b570a2b98c99288b4f7fd23f

I cannot set a value under 'value' (text box does not react when i click on it)

![image](https://github.com/user-attachments/assets/94bb5681-b4d1-4e67-a247-bfe12733fb2d)

**Comment by AcastaPaloma** [comment]
`      self.value_line_edit.setEnabled(False) # To be changed at resolution of Issue #28` - line 1411 in the main branch

By enabling the field, this should resolve this issue. I will try to look into issue #28.
