### ISSUE TITLE
Windowing does not work and suggestion to use min-max instead of level-width

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/slicer-manual-annotation#67]
version: eef16bcb5e84cf73b570a2b98c99288b4f7fd23f

Here's how my image looks like:

![image](https://github.com/user-attachments/assets/d1afbc8f-f116-42d8-a126-5e5c2df4a377)

it ranges approximately from about 0 to 2000

According to my confit, window level is between 1 and 2000, so it should be all right:

![image](https://github.com/user-attachments/assets/d980faa1-15fe-431f-b720-579ee207dc2b)

Changing the level/width doesn't change anything on the appearance of the image.

BTW: I just realized that the windowing specifies 'level' and 'width'. I personally don't find it intuitive (I'd go with 'min-max' range). What does everyone think?

**Comment by maxradx** [comment]
addressed in PR 109.
