### ISSUE TITLE
What is the aim of the package ?

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/slicer-manual-annotation#68]
From what I understand, the goal of this package is to create a slicer module to easily segment pathologies/anatomies on medical images (CT, MRI and more ?).

However, when I look at the code, it seems to rely heavily on multiple **configuration files (.yml)** that are not completely intuitive and its hard to know to what extent these configuration files are customizable:
- [classification_config.yml](https://github.com/neuropoly/slicer-manual-annotation/blob/main/SlicerCART/src/classification_config.yml)
- [general_config.yml](https://github.com/neuropoly/slicer-manual-annotation/blob/main/SlicerCART/src/general_config.yml)
- [keyboard_shortcuts_config.yml](https://github.com/neuropoly/slicer-manual-annotation/blob/main/SlicerCART/src/keyboard_shortcuts_config.yml)
- [label_config.yml](https://github.com/neuropoly/slicer-manual-annotation/blob/main/SlicerCART/src/label_config.yml)

So what I don't get is this:
1. Do we want to allow the user to create/add buttons or short cuts only by modifying the configuration files ? If so, how to do it ? What are the limitations ?
2. Do we want to provide the user with determined configuration files that correspond to different workflows ? (e.g. MRI lesion segmentation and classification, MRI rootlets segmentation, CT edema segmentation...)
3. Why do we have that many configuration files ? Can't we regroup ?

I personally think that these questions need to have a precise answer to clarify the direction of the project. I'm no expert with slicer but currently all the possibilities feel really overwhelming.

**Comment by jcohenadad** [comment]
Agreed-- it comes back to the 'big picture' discussion that we should have as a team, tomorrow and in subsequent meetings.

**Comment by maxradx** [comment]
Will be directly addressed deeply in the updated README.md from [issue 62](https://github.com/neuropoly/slicer-manual-annotation/issues/62). Note that the specific aim of the package is to optimize worklow related to manual annotation, classification and visualization of medical imaging volumes.
