### ISSUE TITLE
Cannot Find SlicerCART.ui file (Linux OS)

### ISSUE THREAD

**Issue by SomeoneInParticular** [neuropoly/slicer-manual-annotation#69]
**Describe the bug**
SlicerCART fails to load its UI elements due to being unable to find `SlicerCART.ui` file.

**To Reproduce**
1. Load into a Linux operating system 
2. Load the module as usual in 3DSlicer 5.2.2
3. Once the module has been loaded and activated, click the "Reload and Test" button; a "Slicer Error" saying the UI file could not be found should appear

**Expected behavior**
The package should load the testing setup

**Screenshots**
The error message:
![Screenshot from 2024-09-23 23-52-05](https://github.com/user-attachments/assets/f1b4d07e-07c9-4193-a9e4-94152f8b0698)

The file's true path (note that the "resource" directory is lower-case, while the error message is asking for a path with an upper-case "Resource" directory)
![Screenshot from 2024-09-23 23-54-07](https://github.com/user-attachments/assets/9bcc8cad-3db3-40ec-9e11-ca1f835aaa05)

**Desktop Information:**
 - OS: PopOS 22.04 LTS (Branch of Ubuntu 22.04 LTS)
 - 3DSlicer v 5.2.2

**Additional context**
I have confirmed that this is just an error in how we name the "resources" folder (it needs to be "Resources", uppercase, to conform with Unix path standards); this is a trivial fix, but will likely break GitHub merges; hence I will create a push and wait until the meeting tomorrow to discuss how to resolve this cleanly without disrupting everyone's existing work. Cheers!

**Comment by laurentletg** [comment]
I can merge the PR. Interestingly, it works on mac (why? also UNIX), will try on a Linux Ubuntu system.
