### ISSUE TITLE
Dark vs light mode automated detection

### ISSUE THREAD

**Issue by maxradx** [neuropoly/slicer-manual-annotation#89]
**Is your feature request related to a problem? Please describe.**
If the user uses Slicer in Darkmode, then some policy may be dark and difficult to read (dark on dark)

**Describe the solution you'd like**
Automated detection and adaptation of the policy colors used in the module according to the 3D Slicer color mode.

**Describe alternatives you've considered**
Insert if statements in the code (not-optimal!)

**Additional context**
An illustrated example.
<img width="542" alt="image" src="https://github.com/user-attachments/assets/0d4b3ae4-5b0b-48b1-bd3c-0b56b1eead8f">

**Comment by maxradx** [comment]
Useful? https://github.com/sjh26/SlicerThemes

**Comment by AcastaPaloma** [comment]
Will check out slicerthemes.
